### PR TITLE
Add TSO500L data sections into v2 samplesheet

### PR DESCRIPTION
**Pull request by alexiswl**
Adds the following sections to the v2 samplesheet for library ids with cttsov2 assays

Note that because we don't prefix these sections with 'Cloud_' they will not be autolaunched. Instead can be parsed through BaseSpace for downstream processing in ICAv2 once the data has been copied over to the ICAv2 project

### CODE REVIEW

**Review by williamputraintan — APPROVED** [review]

**Comment by alexiswl** [comment]
Quick minor update, BaseSpace needs SoftwareVersion in BCLConvert_Settings (have added that in here - [33ed267](https://github.com/umccr/samplesheet-check-backend/pull/49/commits/33ed26746c1fb0c1d176491cf3c7596308248be9))

**Comment by alexiswl** [comment]
~~On hold until we can fix https://github.com/umccr-illumina/ica_v2/issues/171~~ 

Moving forward with PR merge, https://github.com/umccr-illumina/ica_v2/issues/171 doesn't need resolving since we monitor the ICAv2 BCLConvert analysis ID, not the workflow session

**Comment by alexiswl** [comment]
@victorskl will need another push of samplesheetbackend to prod before you generate the lambda to run the bs cli upload TES task

**Comment by victorskl** [comment]
Got it.!

**Comment by victorskl** [comment]
Related https://github.com/umccr/orcabus/issues/135

**Comment by victorskl** [comment]
Related https://github.com/umccr/orcabus/issues/140

**Pull request merged**
