### PR TITLE
2024 Samplesheet Checker

### PR DESCRIPTION
**Pull request by williamputraintan**
- Update dependencies of Python, CDK, and other libraries versions
- Move out from lambda layers and zipped to container approach
- Support output of samplesheet v2 (downloadable from the UI)

### CODE REVIEW

**Comment by williamputraintan** [comment]
I might need help to `cdk deploy` the pipeline in prod account. The pipeline has breaking changes as it will fail not recognising the new folder structure


```
cdk deploy SSCheckBackEndCdkPipeline
```

**Comment by williamputraintan** [comment]
> #### ⚠️ GitGuardian has uncovered 2 secrets following the scan of your pull request.
> Please consider investigating the findings and remediating the incidents. Failure to do so may lead to compromising the associated services or software components.
> 
> 🔎 Detected hardcoded secrets in your pull request
> 🛠 Guidelines to remediate hardcoded secrets
> 🦉 [GitGuardian](https://dashboard.gitguardian.com/auth/login/?utm_medium=checkruns&utm_source=github&utm_campaign=cr1) detects secrets in your source code to help developers and security teams secure the modern development process. You are seeing this because you or someone else with access to this repository has authorized GitGuardian to scan your pull request.Our GitHub checks need improvements? [Share your feedbacks](https://050127dayho.typeform.com/to/KmeAPTMk)!

I marked this as false positive, there were **fake** JWTs deleted from a file.

**Comment by victorskl** [comment]
Reviewing... 
I reckon, this works already well in dev at this point.

**Review by victorskl — APPROVED** [review]
Same. If sscheck get more serious, we should improve a tab better when we have more time; but that's for next year.! Let ship it for now. 😸

**Comment by williamputraintan** [comment]
Merged! Would need to `cdk deploy SSCheckBackEndCdkPipeline` in the prod account to succeed the build

**Pull request merged**
